<Project Sdk="Microsoft.NET.Sdk">

  <!-- TCP/MLLP inbound + outbound endpoint + pooled connection. -->
  <ItemGroup>
    <ProjectReference Include="..\..\Philips.IBE.IBEAgent.Abstractions\Philips.IBE.IBEAgent.Abstractions.csproj" />
    <ProjectReference Include="..\..\Philips.IBE.IBEAgent.Core\Philips.IBE.IBEAgent.Core.csproj" />
  </ItemGroup>

</Project>
