using System.Text;
using System.Text.Json;

// GenTemplates — regenerates config/templates/workflows/*.jsonc from config/catalogData.json so the FSE
// copy-paste workflow starters never drift from the developer's declared Settings.
// Usage: dotnet run --project tools/gen-templates -- [repoRoot]   (repoRoot defaults to the current dir)

var root = args.Length > 0 ? args[0] : Directory.GetCurrentDirectory();
var catalogPath = Path.Combine(root, "config", "catalogData.json");
var outputDir = Path.Combine(root, "config", "templates", "workflows");

if (!File.Exists(catalogPath))
{
    Console.Error.WriteLine($"catalogData.json not found at '{catalogPath}'. Pass the repo root as the first argument.");
    return 1;
}

using var document = JsonDocument.Parse(
    File.ReadAllText(catalogPath),
    new JsonDocumentOptions { CommentHandling = JsonCommentHandling.Skip, AllowTrailingCommas = true });

if (!document.RootElement.TryGetProperty("Catalog", out var catalog) ||
    !catalog.TryGetProperty("Workflows", out var workflows) ||
    workflows.ValueKind != JsonValueKind.Object)
{
    Console.Error.WriteLine("No 'Catalog.Workflows' object found in catalogData.json.");
    return 1;
}

Directory.CreateDirectory(outputDir);

var generated = 0;
foreach (var workflow in workflows.EnumerateObject())
{
    File.WriteAllText(Path.Combine(outputDir, workflow.Name + ".jsonc"), Render(workflow.Name, workflow.Value));
    Console.WriteLine($"Generated {workflow.Name}.jsonc");
    generated++;
}

Console.WriteLine($"Generated {generated} workflow template(s) in '{outputDir}'.");
return 0;

// Emits a copy-paste "Workflow" block: the Use name plus each Setting pre-filled to its Default (or "" when
// required) with a guardrail comment, so the FSE sees exactly the form the developer exposed.
static string Render(string name, JsonElement workflow)
{
    var hasSettings = workflow.TryGetProperty("Settings", out var settings)
        && settings.ValueKind == JsonValueKind.Object
        && settings.EnumerateObject().Any();

    var builder = new StringBuilder();
    builder.AppendLine("// GENERATED by tools/gen-templates from config/catalogData.json — DO NOT EDIT BY HAND.");
    builder.AppendLine("// Paste into a contract's \"Workflow\" field (contractData.json) and tweak the Settings.");
    builder.AppendLine("\"Workflow\": {");
    builder.AppendLine($"  \"Use\": \"{name}\"{(hasSettings ? "," : string.Empty)}");

    if (hasSettings)
    {
        builder.AppendLine("  \"Settings\": {");
        var entries = settings.EnumerateObject().ToList();
        for (var i = 0; i < entries.Count; i++)
        {
            var comma = i < entries.Count - 1 ? "," : string.Empty;
            builder.AppendLine($"    \"{entries[i].Name}\": {DefaultValue(entries[i].Value)}{comma}{Comment(entries[i].Value)}");
        }
        builder.AppendLine("  }");
    }

    builder.AppendLine("}");
    return builder.ToString();
}

static string DefaultValue(JsonElement setting)
    => setting.TryGetProperty("Default", out var def) && def.ValueKind == JsonValueKind.String
        ? $"\"{def.GetString()}\""
        : "\"\"";   // required (no default) — the FSE must fill this in

static string Comment(JsonElement setting)
{
    var parts = new List<string>();
    if (setting.TryGetProperty("Description", out var description) && description.GetString() is { Length: > 0 } text)
    {
        parts.Add(text);
    }

    var guards = new List<string>();
    if (setting.TryGetProperty("Min", out var min)) guards.Add($"min {min}");
    if (setting.TryGetProperty("Max", out var max)) guards.Add($"max {max}");
    if (setting.TryGetProperty("Allowed", out var allowed) && allowed.ValueKind == JsonValueKind.Array)
    {
        guards.Add("one of [" + string.Join(", ", allowed.EnumerateArray().Select(a => a.GetString())) + "]");
    }
    if (setting.TryGetProperty("Kind", out var kind) && kind.GetString() is { Length: > 0 } kindText)
    {
        guards.Add(kindText);
    }
    if (guards.Count > 0)
    {
        parts.Add("(" + string.Join("; ", guards) + ")");
    }

    if (!(setting.TryGetProperty("Default", out var d) && d.ValueKind == JsonValueKind.String))
    {
        parts.Add("REQUIRED");
    }

    return parts.Count > 0 ? "   // " + string.Join(" ", parts) : string.Empty;
}
